openapi: 3.0.0
info:
  title: Volontarion API
  description: API documentation for the Volontarion platform.
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /registrazioneVolontario:
    post:
      summary: Register a new volunteer
      requestBody:
        description: Volunteer registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        "201":
          description: Volunteer registered successfully
        "400":
          description: Validation error

  /login:
    post:
      summary: Login for a volunteer
      requestBody:
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: Login successful
        "401":
          description: Invalid credentials

  /getVolontari:
    get:
      summary: Retrieve all volunteers
      security:
        - cookieAuth: []
      responses:
        "200":
          description: List of volunteers
        "401":
          description: Unauthorized

  /getCurrentVolontario:
    get:
      summary: Get details of the current volunteer
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Volunteer details
        "401":
          description: Unauthorized

  /modifyProfilePicture:
    put:
      summary: Modify volunteer's profile picture
      security:
        - cookieAuth: []
      requestBody:
        description: New profile picture data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Profile picture updated successfully
        "400":
          description: Invalid image data
        "401":
          description: Unauthorized

  /modifyDescription:
    put:
      summary: Modify volunteer's description
      security:
        - cookieAuth: []
      requestBody:
        description: New description
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
      responses:
        "200":
          description: Description updated successfully
        "400":
          description: Invalid description
        "401":
          description: Unauthorized

  /modifySkills:
    put:
      summary: Modify volunteer's skills
      security:
        - cookieAuth: []
      requestBody:
        description: New skills
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                skills:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Skills updated successfully
        "400":
          description: Invalid skills data
        "401":
          description: Unauthorized

  /deleteAccount:
    delete:
      summary: Delete volunteer's account
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Account deleted successfully
        "401":
          description: Unauthorized

  /logout:
    get:
      summary: Logout the current user
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Logout successful
        "401":
          description: Unauthorized

  /getProfilePicture:
    get:
      summary: Retrieve volunteer's profile picture
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Profile picture retrieved successfully
        "401":
          description: Unauthorized

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt
